version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"
  gateway:
    image: renskloosterman/gateway:latest
    ports:
      - 8080:8080
  tweet-service:
    image: renskloosterman/tweet-service:latest
    ports:
      - 8081:8080
  profile-service:
    image: renskloosterman/profile-service:latest
    ports:
      - 8082:8080
  relation-service:
    image: renskloosterman/social-graph-service:latest
    ports:
      - 8083:8080
