version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 30s
      retries: 3
  gateway:
    image: renskloosterman/gateway:latest
    ports:
      - 8080:8080
    depends_on:
        - rabbitmq
    network_mode: "host"
  tweet-service:
    image: renskloosterman/tweet-service:latest
    ports:
      - 8081:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
  profile-service:
    image: renskloosterman/profile-service:latest
    ports:
      - 8082:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
  relation-service:
    image: renskloosterman/relation-service:latest
    ports:
      - 8083:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
