name: Trigger auto deployment for kwetter-gateway

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kwetter-gateway-AutoDeployTrigger-e0ea6612-654a-494c-af20-42655cb34738.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.KWETTERGATEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.KWETTERGATEWAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: renskloosterman2001@live.nl/kwetter-gateway:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KWETTERGATEWAY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kwetter-gateway -g kwetter-resource-group --server docker.io --username  ${{ secrets.KWETTERGATEWAY_REGISTRY_USERNAME }} --password ${{ secrets.KWETTERGATEWAY_REGISTRY_PASSWORD }}
            az containerapp update -n kwetter-gateway -g kwetter-resource-group --image renskloosterman2001@live.nl/kwetter-gateway:${{ github.sha }}
